### ISSUE TITLE
Template, header, footer, variables and front matter

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/this-month-in-reactive-graph#8]
### Goal

Use templates for creating new issues

### Tasks

- [x] Replace variables
- [x] Add a reusable header template with variables and include it
- [x] Add a reusable footer template with variables and include it
- [x] Create an empty template that can be cloned for each new issue
